/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.connection;
import database.Database;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import entity.Informasi;
import javax.swing.JFrame;
import javax.swing.JLabel;
import entity.Validasi;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author BLESSY
 */

public class AdminInformasi extends javax.swing.JFrame {

    private Connection conn;
    private PreparedStatement pstmt;
    private Statement stat;
    private ResultSet rs;
    private boolean validasi = true;
    private static String judul;
    private static String username;

    
    /**
     * Creates new form AdminInformasi
     */
    public AdminInformasi() {
        initComponents();
        conn = connection.getConnection();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
     public void close() {
//        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
//        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    this.dispose();
    }

    public static void openAdminInformasi(String judul) {
        AdminInformasi.judul = judul;
        main();
    }

    public static void main(String[] args) {
        openAdminInformasi("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        dashboardSidePanel = new javax.swing.JLabel();
        insertSidePanel = new javax.swing.JPanel();
        insertSidePanel2 = new javax.swing.JLabel();
        deleteSidePanel = new javax.swing.JPanel();
        deleteSidePanel2 = new javax.swing.JLabel();
        logoutSidePanel2 = new javax.swing.JPanel();
        logoutSidePanel = new javax.swing.JLabel();
        viewSidePanel1 = new javax.swing.JPanel();
        viewSidePanel4 = new javax.swing.JLabel();
        viewSidePanel2 = new javax.swing.JPanel();
        viewSidePanel5 = new javax.swing.JLabel();
        pmklLogo = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        KeteranganVolunteerPanel = new javax.swing.JPanel();
        keteranganVolunteerJudulPanel = new javax.swing.JPanel();
        informasiJudulLabel = new javax.swing.JLabel();
        judulLabel = new javax.swing.JLabel();
        keteranganKegiatanLabel = new javax.swing.JLabel();
        alasanHScrollPane = new javax.swing.JScrollPane();
        keteranganKegiatanTextArea = new javax.swing.JTextArea();
        judulTextField = new javax.swing.JTextField();
        InsertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dashboardSidePanel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        dashboardSidePanel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardSidePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardSidePanel.setText("DASHBOARD");
        dashboardSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardSidePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        insertSidePanel.setBackground(new java.awt.Color(153, 153, 153));
        insertSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertSidePanelMouseClicked(evt);
            }
        });

        insertSidePanel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        insertSidePanel2.setForeground(new java.awt.Color(255, 255, 255));
        insertSidePanel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insertSidePanel2.setText("INPUT DATA");
        insertSidePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertSidePanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout insertSidePanelLayout = new javax.swing.GroupLayout(insertSidePanel);
        insertSidePanel.setLayout(insertSidePanelLayout);
        insertSidePanelLayout.setHorizontalGroup(
            insertSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertSidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertSidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        insertSidePanelLayout.setVerticalGroup(
            insertSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertSidePanel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteSidePanel.setBackground(new java.awt.Color(153, 153, 153));

        deleteSidePanel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        deleteSidePanel2.setForeground(new java.awt.Color(255, 255, 255));
        deleteSidePanel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteSidePanel2.setText("HAPUS DATA");
        deleteSidePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteSidePanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout deleteSidePanelLayout = new javax.swing.GroupLayout(deleteSidePanel);
        deleteSidePanel.setLayout(deleteSidePanelLayout);
        deleteSidePanelLayout.setHorizontalGroup(
            deleteSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteSidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteSidePanelLayout.setVerticalGroup(
            deleteSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteSidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteSidePanel2)
                .addContainerGap())
        );

        logoutSidePanel2.setBackground(new java.awt.Color(153, 153, 153));
        logoutSidePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutSidePanel2MouseClicked(evt);
            }
        });

        logoutSidePanel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        logoutSidePanel.setForeground(new java.awt.Color(255, 255, 255));
        logoutSidePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutSidePanel.setText("LOGOUT");
        logoutSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutSidePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logoutSidePanel2Layout = new javax.swing.GroupLayout(logoutSidePanel2);
        logoutSidePanel2.setLayout(logoutSidePanel2Layout);
        logoutSidePanel2Layout.setHorizontalGroup(
            logoutSidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutSidePanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        logoutSidePanel2Layout.setVerticalGroup(
            logoutSidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutSidePanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        viewSidePanel1.setBackground(new java.awt.Color(153, 153, 153));
        viewSidePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSidePanel1MouseClicked(evt);
            }
        });

        viewSidePanel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        viewSidePanel4.setForeground(new java.awt.Color(255, 255, 255));
        viewSidePanel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewSidePanel4.setText("VIEW DATA");
        viewSidePanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSidePanel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viewSidePanel1Layout = new javax.swing.GroupLayout(viewSidePanel1);
        viewSidePanel1.setLayout(viewSidePanel1Layout);
        viewSidePanel1Layout.setHorizontalGroup(
            viewSidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSidePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewSidePanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewSidePanel1Layout.setVerticalGroup(
            viewSidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewSidePanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        viewSidePanel2.setBackground(new java.awt.Color(153, 153, 153));
        viewSidePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSidePanel2MouseClicked(evt);
            }
        });

        viewSidePanel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        viewSidePanel5.setForeground(new java.awt.Color(255, 255, 255));
        viewSidePanel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewSidePanel5.setText("VIEW");
        viewSidePanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSidePanel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viewSidePanel2Layout = new javax.swing.GroupLayout(viewSidePanel2);
        viewSidePanel2.setLayout(viewSidePanel2Layout);
        viewSidePanel2Layout.setHorizontalGroup(
            viewSidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSidePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewSidePanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewSidePanel2Layout.setVerticalGroup(
            viewSidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewSidePanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pmklLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pmkl_k.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(pmklLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewSidePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewSidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutSidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pmklLogo)
                .addGap(92, 92, 92)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insertSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(deleteSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewSidePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewSidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(logoutSidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 940));

        jPanel8.setBackground(new java.awt.Color(255, 102, 0));

        jLabel6.setBackground(new java.awt.Color(242, 237, 215));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INSERT INFORMASI [ADMIN]");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel6)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1300, 80));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        KeteranganVolunteerPanel.setBackground(new java.awt.Color(204, 255, 204));
        KeteranganVolunteerPanel.setPreferredSize(new java.awt.Dimension(650, 700));

        keteranganVolunteerJudulPanel.setBackground(new java.awt.Color(153, 153, 153));
        keteranganVolunteerJudulPanel.setPreferredSize(new java.awt.Dimension(650, 100));

        informasiJudulLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        informasiJudulLabel.setForeground(new java.awt.Color(255, 255, 255));
        informasiJudulLabel.setText("Informasi Umum");

        javax.swing.GroupLayout keteranganVolunteerJudulPanelLayout = new javax.swing.GroupLayout(keteranganVolunteerJudulPanel);
        keteranganVolunteerJudulPanel.setLayout(keteranganVolunteerJudulPanelLayout);
        keteranganVolunteerJudulPanelLayout.setHorizontalGroup(
            keteranganVolunteerJudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keteranganVolunteerJudulPanelLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(informasiJudulLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        keteranganVolunteerJudulPanelLayout.setVerticalGroup(
            keteranganVolunteerJudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keteranganVolunteerJudulPanelLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(informasiJudulLabel))
        );

        judulLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        judulLabel.setText("Judul");

        keteranganKegiatanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        keteranganKegiatanLabel.setText("Keterangan Kegiatan");

        keteranganKegiatanTextArea.setColumns(20);
        keteranganKegiatanTextArea.setRows(5);
        alasanHScrollPane.setViewportView(keteranganKegiatanTextArea);

        judulTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulTextFieldActionPerformed(evt);
            }
        });
        judulTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                judulTextFieldKeyReleased(evt);
            }
        });

        InsertButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsertButton.setForeground(new java.awt.Color(229, 88, 7));
        InsertButton.setText("Insert Information");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KeteranganVolunteerPanelLayout = new javax.swing.GroupLayout(KeteranganVolunteerPanel);
        KeteranganVolunteerPanel.setLayout(KeteranganVolunteerPanelLayout);
        KeteranganVolunteerPanelLayout.setHorizontalGroup(
            KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeteranganVolunteerPanelLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeteranganVolunteerPanelLayout.createSequentialGroup()
                        .addGroup(KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(keteranganKegiatanLabel))
                        .addGap(18, 18, 18)
                        .addGroup(KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alasanHScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeteranganVolunteerPanelLayout.createSequentialGroup()
                        .addComponent(InsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)))
                .addGap(137, 137, 137))
            .addComponent(keteranganVolunteerJudulPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        KeteranganVolunteerPanelLayout.setVerticalGroup(
            KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeteranganVolunteerPanelLayout.createSequentialGroup()
                .addComponent(keteranganVolunteerJudulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judulLabel))
                .addGap(18, 18, 18)
                .addGroup(KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keteranganKegiatanLabel)
                    .addGroup(KeteranganVolunteerPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(alasanHScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(InsertButton)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(KeteranganVolunteerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(KeteranganVolunteerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 1300, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        // TODO add your handling code here:
        if (!ValidasiNull()) {
    JOptionPane.showMessageDialog(null, "Semua input harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
    }
    if (ValidasiInput()) {
        try {                
            Informasi information = new Informasi();
            information.setJudul(judulTextField.getText());
            information.setKeteranganKegiatan(keteranganKegiatanTextArea.getText());
            
            // Call the insertContent method of the Database class
                int statusCode = Database.getInstance().insertInformasi(information);

                // Handle the insert result based on the status code
                switch (statusCode) {
                    case 0:
                        // Insert failed
                        JOptionPane.showMessageDialog(null, "Failed to insert data. Please try again.", "Error",
                                JOptionPane.ERROR_MESSAGE);
                        break;
                    case 1:
                        // Data inserted successfully
                        JOptionPane.showMessageDialog(null, "Data inserted successfully!");
                        // Add any additional logic or navigation after successful insertion
                        break;
                }
         } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "An error occurred. Please try again later.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Invalid input for numeric fields.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Data yang anda Inputkan Belum Sesuai!", "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_InsertButtonActionPerformed

    public Boolean ValidasiInput(){
        if(Validasi.cekJudul(judulTextField.getText())==false){
            return false;
        }
        return true;
    }
    
    public Boolean ValidasiNull() {
    if (judulTextField.getText().isEmpty()) {
        return false;
    }
    if (keteranganKegiatanTextArea.getText().isEmpty()) {
        return false;
    }
    return true;
}
    
    private void judulTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulTextFieldActionPerformed

    private void judulTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_judulTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_judulTextFieldKeyReleased

    private void viewSidePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSidePanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSidePanel2MouseClicked

    private void viewSidePanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSidePanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSidePanel5MouseClicked

    private void viewSidePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSidePanel1MouseClicked
        // TODO add your handling code here:
        close();
        AdminView.openAdminView(username);
    }//GEN-LAST:event_viewSidePanel1MouseClicked

    private void viewSidePanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSidePanel4MouseClicked
        // TODO add your handling code here:
        close();
        AdminView.openAdminView(username);
    }//GEN-LAST:event_viewSidePanel4MouseClicked

    private void logoutSidePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutSidePanel2MouseClicked
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        // Check the user's choice
        if (option == JOptionPane.YES_OPTION) {
            close();
            SignIn.openSignIn();
        }
    }//GEN-LAST:event_logoutSidePanel2MouseClicked

    private void logoutSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutSidePanelMouseClicked
        // TODO add your handling code here:
        // Display a confirmation dialog
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        // Check the user's choice
        if (option == JOptionPane.YES_OPTION) {
            close();
            SignIn.openSignIn();
        }
    }//GEN-LAST:event_logoutSidePanelMouseClicked

    private void deleteSidePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSidePanel2MouseClicked
        // TODO add your handling code here:
        close();
        AdminDelete.openAdminDelete(username);
    }//GEN-LAST:event_deleteSidePanel2MouseClicked

    private void insertSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertSidePanelMouseClicked
        // TODO add your handling code here:
        close();
        AdminInsert.openAdminInsert(username);
    }//GEN-LAST:event_insertSidePanelMouseClicked

    private void insertSidePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertSidePanel2MouseClicked
        // TODO add your handling code here:
        close();
        AdminInsert.openAdminInsert(username);
    }//GEN-LAST:event_insertSidePanel2MouseClicked

    private void dashboardSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardSidePanelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Anda sudah berada disini", "Sudah sampai", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_dashboardSidePanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInformasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInformasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInformasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInformasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInformasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertButton;
    private javax.swing.JPanel KeteranganVolunteerPanel;
    private javax.swing.JScrollPane alasanHScrollPane;
    private javax.swing.JLabel dashboardSidePanel;
    private javax.swing.JPanel deleteSidePanel;
    private javax.swing.JLabel deleteSidePanel2;
    private javax.swing.JLabel informasiJudulLabel;
    private javax.swing.JPanel insertSidePanel;
    private javax.swing.JLabel insertSidePanel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JTextField judulTextField;
    private javax.swing.JLabel keteranganKegiatanLabel;
    private javax.swing.JTextArea keteranganKegiatanTextArea;
    private javax.swing.JPanel keteranganVolunteerJudulPanel;
    private javax.swing.JLabel logoutSidePanel;
    private javax.swing.JPanel logoutSidePanel2;
    private javax.swing.JLabel pmklLogo;
    private javax.swing.JPanel viewSidePanel1;
    private javax.swing.JPanel viewSidePanel2;
    private javax.swing.JLabel viewSidePanel4;
    private javax.swing.JLabel viewSidePanel5;
    // End of variables declaration//GEN-END:variables
}
