/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.connection;
import gui.AdminDashboard;
import gui.AdminDelete;
import gui.AdminView;
import database.Database;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import entity.Content;
import entity.Validasi;
import java.sql.SQLException;

/**
 *
 * @author BLESSY
 */

public class AdminInsert extends javax.swing.JFrame {

    private Connection conn;
    private PreparedStatement pstmt;
    private Statement stat;
    private ResultSet rs;
    private boolean validasi = true;
    private static String username;

    public AdminInsert() {
        initComponents();
        conn = connection.getConnection();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void close() {
//        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
//        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    this.dispose();
    }

    public static void openAdminInsert(String username) {
        AdminInsert.username = username;
        main();
    }

    public static void main(String[] args) {
        openAdminInsert("1");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorNamaPencacah = new javax.swing.JLabel();
        errorNamaPengawas = new javax.swing.JLabel();
        errorTanggalPencacahan = new javax.swing.JLabel();
        errorTanggalPengawasan = new javax.swing.JLabel();
        errorNamaResponden = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        DataVolunteerPanel = new javax.swing.JPanel();
        namaLengkapLabel = new javax.swing.JLabel();
        namaLengkapTextField = new javax.swing.JTextField();
        UmurLabel = new javax.swing.JLabel();
        umurTextField = new javax.swing.JTextField();
        JenisKelaminLabel = new javax.swing.JLabel();
        jenisKelamin = new javax.swing.JComboBox<>();
        dataVolunteerJudulPanel = new javax.swing.JPanel();
        KIPJudulLabel1 = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        nimTextField = new javax.swing.JTextField();
        kelasLabel = new javax.swing.JLabel();
        kelasTextField = new javax.swing.JTextField();
        asalDaerahLabel = new javax.swing.JLabel();
        asalDaerahTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        KeteranganVolunteerPanel = new javax.swing.JPanel();
        keteranganVolunteerJudulPanel = new javax.swing.JPanel();
        akseLayananJudulLabel = new javax.swing.JLabel();
        tanggalMasukLabel = new javax.swing.JLabel();
        alasanLabel = new javax.swing.JLabel();
        alasanHScrollPane = new javax.swing.JScrollPane();
        alasanTextArea = new javax.swing.JTextArea();
        tanggalMasukTextField = new javax.swing.JTextField();
        hapusButton = new javax.swing.JButton();
        InsertButton = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        dashboardSidePanel = new javax.swing.JLabel();
        insertSidePanel = new javax.swing.JPanel();
        insertSidePanel2 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        deleteSidePanel = new javax.swing.JLabel();
        viewSidePanel = new javax.swing.JPanel();
        viewSidePanel3 = new javax.swing.JLabel();
        logoutSidePanel2 = new javax.swing.JPanel();
        logoutSidePanel = new javax.swing.JLabel();

        errorNamaPencacah.setForeground(new java.awt.Color(255, 51, 51));
        errorNamaPencacah.setText("Karakter harus lebih dari 4 dan kurang dari 26!");

        errorNamaPengawas.setForeground(new java.awt.Color(255, 51, 51));
        errorNamaPengawas.setText("Karakter harus lebih dari 4 dan kurang dari 26!");

        errorTanggalPencacahan.setForeground(new java.awt.Color(255, 51, 51));
        errorTanggalPencacahan.setText("Tanggal harus sama dengan tanggal hari ini!");

        errorTanggalPengawasan.setForeground(new java.awt.Color(255, 51, 51));
        errorTanggalPengawasan.setText("Tanggal harus sama dengan tanggal hari ini!");

        errorNamaResponden.setForeground(new java.awt.Color(255, 51, 51));
        errorNamaResponden.setText("Karakter harus lebih dari 4 dan kurang dari 26!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 102, 0));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INSERT [ADMIN]");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jLabel7)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1260, 80));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);

        DataVolunteerPanel.setBackground(new java.awt.Color(204, 255, 204));

        namaLengkapLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaLengkapLabel.setText("Nama Lengkap");

        namaLengkapTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaLengkapTextFieldActionPerformed(evt);
            }
        });
        namaLengkapTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namaLengkapTextFieldKeyReleased(evt);
            }
        });

        UmurLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UmurLabel.setText("Umur");

        JenisKelaminLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JenisKelaminLabel.setText("Jenis kelamin");

        jenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        jenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisKelaminActionPerformed(evt);
            }
        });

        dataVolunteerJudulPanel.setBackground(new java.awt.Color(153, 153, 153));

        KIPJudulLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        KIPJudulLabel1.setForeground(new java.awt.Color(255, 255, 255));
        KIPJudulLabel1.setText("Blok I. Data Volunteer");

        javax.swing.GroupLayout dataVolunteerJudulPanelLayout = new javax.swing.GroupLayout(dataVolunteerJudulPanel);
        dataVolunteerJudulPanel.setLayout(dataVolunteerJudulPanelLayout);
        dataVolunteerJudulPanelLayout.setHorizontalGroup(
            dataVolunteerJudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataVolunteerJudulPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KIPJudulLabel1)
                .addGap(81, 81, 81))
        );
        dataVolunteerJudulPanelLayout.setVerticalGroup(
            dataVolunteerJudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataVolunteerJudulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KIPJudulLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nimLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nimLabel.setText("NIM");

        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });
        nimTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nimTextFieldKeyReleased(evt);
            }
        });

        kelasLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kelasLabel.setText("Kelas");

        kelasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasTextFieldActionPerformed(evt);
            }
        });
        kelasTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kelasTextFieldKeyReleased(evt);
            }
        });

        asalDaerahLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        asalDaerahLabel.setText("Asal Daerah");

        asalDaerahTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asalDaerahTextFieldActionPerformed(evt);
            }
        });
        asalDaerahTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                asalDaerahTextFieldKeyReleased(evt);
            }
        });

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyReleased(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabel.setText("Email");

        javax.swing.GroupLayout DataVolunteerPanelLayout = new javax.swing.GroupLayout(DataVolunteerPanel);
        DataVolunteerPanel.setLayout(DataVolunteerPanelLayout);
        DataVolunteerPanelLayout.setHorizontalGroup(
            DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataVolunteerJudulPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DataVolunteerPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataVolunteerPanelLayout.createSequentialGroup()
                        .addComponent(JenisKelaminLabel)
                        .addGap(13, 13, 13))
                    .addGroup(DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataVolunteerPanelLayout.createSequentialGroup()
                            .addComponent(UmurLabel)
                            .addGap(60, 60, 60))
                        .addComponent(nimLabel)
                        .addComponent(namaLengkapLabel)
                        .addComponent(kelasLabel)
                        .addComponent(asalDaerahLabel)
                        .addComponent(emailLabel)))
                .addGap(39, 39, 39)
                .addGroup(DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(umurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(namaLengkapTextField)
                        .addComponent(nimTextField)
                        .addComponent(kelasTextField)
                        .addComponent(asalDaerahTextField)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        DataVolunteerPanelLayout.setVerticalGroup(
            DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataVolunteerPanelLayout.createSequentialGroup()
                .addComponent(dataVolunteerJudulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLengkapLabel)
                    .addComponent(namaLengkapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nimLabel)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasLabel)
                    .addComponent(kelasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asalDaerahLabel)
                    .addComponent(asalDaerahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UmurLabel)
                    .addComponent(umurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DataVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JenisKelaminLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        KeteranganVolunteerPanel.setBackground(new java.awt.Color(204, 255, 204));
        KeteranganVolunteerPanel.setPreferredSize(new java.awt.Dimension(650, 700));

        keteranganVolunteerJudulPanel.setBackground(new java.awt.Color(153, 153, 153));
        keteranganVolunteerJudulPanel.setPreferredSize(new java.awt.Dimension(650, 100));

        akseLayananJudulLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        akseLayananJudulLabel.setForeground(new java.awt.Color(255, 255, 255));
        akseLayananJudulLabel.setText("Blok II. Keterangan Volunteer");

        javax.swing.GroupLayout keteranganVolunteerJudulPanelLayout = new javax.swing.GroupLayout(keteranganVolunteerJudulPanel);
        keteranganVolunteerJudulPanel.setLayout(keteranganVolunteerJudulPanelLayout);
        keteranganVolunteerJudulPanelLayout.setHorizontalGroup(
            keteranganVolunteerJudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keteranganVolunteerJudulPanelLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(akseLayananJudulLabel)
                .addGap(60, 60, 60))
        );
        keteranganVolunteerJudulPanelLayout.setVerticalGroup(
            keteranganVolunteerJudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keteranganVolunteerJudulPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(akseLayananJudulLabel)
                .addContainerGap())
        );

        tanggalMasukLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tanggalMasukLabel.setText("Tanggal Masuk");

        alasanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alasanLabel.setText("Alasan Masuk");

        alasanTextArea.setColumns(20);
        alasanTextArea.setRows(5);
        alasanHScrollPane.setViewportView(alasanTextArea);

        tanggalMasukTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalMasukTextFieldActionPerformed(evt);
            }
        });
        tanggalMasukTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tanggalMasukTextFieldKeyReleased(evt);
            }
        });

        hapusButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(229, 88, 7));
        hapusButton.setText("Hapus Data");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        InsertButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsertButton.setForeground(new java.awt.Color(229, 88, 7));
        InsertButton.setText("Insert");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KeteranganVolunteerPanelLayout = new javax.swing.GroupLayout(KeteranganVolunteerPanel);
        KeteranganVolunteerPanel.setLayout(KeteranganVolunteerPanelLayout);
        KeteranganVolunteerPanelLayout.setHorizontalGroup(
            KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeteranganVolunteerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeteranganVolunteerPanelLayout.createSequentialGroup()
                        .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InsertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(KeteranganVolunteerPanelLayout.createSequentialGroup()
                        .addGroup(KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tanggalMasukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alasanLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alasanHScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalMasukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(KeteranganVolunteerPanelLayout.createSequentialGroup()
                .addComponent(keteranganVolunteerJudulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        KeteranganVolunteerPanelLayout.setVerticalGroup(
            KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeteranganVolunteerPanelLayout.createSequentialGroup()
                .addComponent(keteranganVolunteerJudulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeteranganVolunteerPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(alasanHScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KeteranganVolunteerPanelLayout.createSequentialGroup()
                        .addGroup(KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanggalMasukLabel)
                            .addComponent(tanggalMasukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(alasanLabel)))
                .addGap(68, 68, 68)
                .addGroup(KeteranganVolunteerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusButton)
                    .addComponent(InsertButton))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(DataVolunteerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KeteranganVolunteerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DataVolunteerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KeteranganVolunteerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 1260, 780));

        jPanel15.setBackground(new java.awt.Color(255, 102, 0));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pmkl_k.jpg"))); // NOI18N
        jPanel15.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 80, -1));

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));

        dashboardSidePanel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        dashboardSidePanel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardSidePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardSidePanel.setText("DASHBOARD");
        dashboardSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardSidePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addComponent(dashboardSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel15.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 290, 40));

        insertSidePanel.setBackground(new java.awt.Color(153, 153, 153));
        insertSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertSidePanelMouseClicked(evt);
            }
        });

        insertSidePanel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        insertSidePanel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insertSidePanel2.setText("INSERT");
        insertSidePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertSidePanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout insertSidePanelLayout = new javax.swing.GroupLayout(insertSidePanel);
        insertSidePanel.setLayout(insertSidePanelLayout);
        insertSidePanelLayout.setHorizontalGroup(
            insertSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertSidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertSidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        insertSidePanelLayout.setVerticalGroup(
            insertSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertSidePanel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.add(insertSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 290, -1));

        jPanel21.setBackground(new java.awt.Color(153, 153, 153));

        deleteSidePanel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        deleteSidePanel.setForeground(new java.awt.Color(255, 255, 255));
        deleteSidePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteSidePanel.setText("DELETE");
        deleteSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteSidePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteSidePanel)
                .addContainerGap())
        );

        jPanel15.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 290, -1));

        viewSidePanel.setBackground(new java.awt.Color(153, 153, 153));
        viewSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSidePanelMouseClicked(evt);
            }
        });

        viewSidePanel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        viewSidePanel3.setForeground(new java.awt.Color(255, 255, 255));
        viewSidePanel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewSidePanel3.setText("VIEW");
        viewSidePanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSidePanel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viewSidePanelLayout = new javax.swing.GroupLayout(viewSidePanel);
        viewSidePanel.setLayout(viewSidePanelLayout);
        viewSidePanelLayout.setHorizontalGroup(
            viewSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewSidePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewSidePanelLayout.setVerticalGroup(
            viewSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSidePanelLayout.createSequentialGroup()
                .addComponent(viewSidePanel3)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel15.add(viewSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 290, 40));

        logoutSidePanel2.setBackground(new java.awt.Color(153, 153, 153));
        logoutSidePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutSidePanel2MouseClicked(evt);
            }
        });

        logoutSidePanel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        logoutSidePanel.setForeground(new java.awt.Color(255, 255, 255));
        logoutSidePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutSidePanel.setText("LOGOUT");
        logoutSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutSidePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logoutSidePanel2Layout = new javax.swing.GroupLayout(logoutSidePanel2);
        logoutSidePanel2.setLayout(logoutSidePanel2Layout);
        logoutSidePanel2Layout.setHorizontalGroup(
            logoutSidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutSidePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutSidePanel2Layout.setVerticalGroup(
            logoutSidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutSidePanel2Layout.createSequentialGroup()
                .addComponent(logoutSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel15.add(logoutSidePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 290, 40));

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaLengkapTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaLengkapTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaLengkapTextFieldActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        // TODO add your handling code here:
        if (!ValidasiNull()) {
    JOptionPane.showMessageDialog(null, "Semua input harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}
if (ValidasiInput()) {
    try {                
        Content content = new Content();
        content.setNamaLengkap(namaLengkapTextField.getText());
        content.setNim(nimTextField.getText());
        content.setKelas(kelasTextField.getText());
        content.setAsalDaerah(asalDaerahTextField.getText());
        content.setEmail(emailTextField.getText());
        content.setUmur(umurTextField.getText());
        int kode = jenisKelamin.getSelectedIndex() + 1;
        content.setJenisKelamin(String.valueOf(kode));
        content.setTanggalMasuk(tanggalMasukTextField.getText());
        content.setAlasan(alasanTextArea.getText());

                // Call the insertContent method of the Database class
                int statusCode = Database.getInstance().insertContent(content);

                // Handle the insert result based on the status code
                switch (statusCode) {
                    case 0:
                        // Insert failed
                        JOptionPane.showMessageDialog(null, "Failed to insert data. Please try again.", "Error",
                                JOptionPane.ERROR_MESSAGE);
                        break;
                    case 1:
                        // Data inserted successfully
                        JOptionPane.showMessageDialog(null, "Data inserted successfully!");
                        // Add any additional logic or navigation after successful insertion
                        break;
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "An error occurred. Please try again later.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Invalid input for numeric fields.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Data yang anda Inputkan Belum Sesuai!", "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void hapus(){
        Content content = new Content();
        namaLengkapTextField.setText("");
        nimTextField.setText("");
        kelasTextField.setText("");
        asalDaerahTextField.setText("");
        emailTextField.setText("");
        umurTextField.setText("");
        jenisKelamin.setSelectedIndex(-1); // Assuming jenisKelamin is a JComboBox
        
        tanggalMasukTextField.setText("");
        alasanTextArea.setText("");
    }
    
    public Boolean ValidasiInput(){
        if(Validasi.cekNamaLengkap(namaLengkapTextField.getText())==false){
            return false;
        }
        
//        if(!Validasi.cekUmur(umurTextField.getText())==false){
//           return false;
//       }
        return true;
    }
    
    public Boolean ValidasiNull() {
    if (namaLengkapTextField.getText().isEmpty()) {
        return false;
    }
    if (nimTextField.getText().isEmpty()) {
        return false;
    }
    if (kelasTextField.getText().isEmpty()) {
        return false;
    }
    if (asalDaerahTextField.getText().isEmpty()) {
        return false;
    }
    if (emailTextField.getText().isEmpty()) {
        return false;
    }
    if (umurTextField.getText().isEmpty()) {
        return false;
    }
    if (jenisKelamin.getSelectedIndex() == -1) { // Assuming jenisKelamin is a JComboBox
        return false;
    }
    if (tanggalMasukTextField.getText().isEmpty()) {
        return false;
    }
    if (alasanTextArea.getText().isEmpty()) {
        return false;
    }
    return true;
}
      
    
    private void dashboardSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardSidePanelMouseClicked
        // TODO add your handling code here:
        close();
        AdminDashboard.openAdminDashboard(username);
    }//GEN-LAST:event_dashboardSidePanelMouseClicked

    private void insertSidePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertSidePanel2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Anda sudah berada disini", "Sudah sampai", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_insertSidePanel2MouseClicked

    private void insertSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertSidePanelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Anda sudah berada disini", "Sudah sampai", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_insertSidePanelMouseClicked

    private void deleteSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSidePanelMouseClicked
        // TODO add your handling code here:
        close();
        AdminDelete.openAdminDelete(username);
    }//GEN-LAST:event_deleteSidePanelMouseClicked

    private void viewSidePanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSidePanel3MouseClicked
        // TODO add your handling code here:
        close();
        AdminView.openAdminView(username);
    }//GEN-LAST:event_viewSidePanel3MouseClicked

    private void viewSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSidePanelMouseClicked
        // TODO add your handling code here:
        close();
        AdminView.openAdminView(username);
    }//GEN-LAST:event_viewSidePanelMouseClicked

    private void logoutSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutSidePanelMouseClicked
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        // Check the user's choice
        if (option == JOptionPane.YES_OPTION) {
            close();
            SignIn.openSignIn();
        }
    }//GEN-LAST:event_logoutSidePanelMouseClicked

    private void logoutSidePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutSidePanel2MouseClicked
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        // Check the user's choice
        if (option == JOptionPane.YES_OPTION) {
            close();
            SignIn.openSignIn();
        }
    }//GEN-LAST:event_logoutSidePanel2MouseClicked

    private void jenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisKelaminActionPerformed

    private void namaLengkapTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaLengkapTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_namaLengkapTextFieldKeyReleased

    private void tanggalMasukTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalMasukTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalMasukTextFieldActionPerformed

    private void tanggalMasukTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tanggalMasukTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalMasukTextFieldKeyReleased

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed

    private void nimTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nimTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldKeyReleased

    private void kelasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasTextFieldActionPerformed

    private void kelasTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kelasTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasTextFieldKeyReleased

    private void asalDaerahTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asalDaerahTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asalDaerahTextFieldActionPerformed

    private void asalDaerahTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_asalDaerahTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_asalDaerahTextFieldKeyReleased

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void emailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataVolunteerPanel;
    private javax.swing.JButton InsertButton;
    private javax.swing.JLabel JenisKelaminLabel;
    private javax.swing.JLabel KIPJudulLabel1;
    private javax.swing.JPanel KeteranganVolunteerPanel;
    private javax.swing.JLabel UmurLabel;
    private javax.swing.JLabel akseLayananJudulLabel;
    private javax.swing.JScrollPane alasanHScrollPane;
    private javax.swing.JLabel alasanLabel;
    private javax.swing.JTextArea alasanTextArea;
    private javax.swing.JLabel asalDaerahLabel;
    private javax.swing.JTextField asalDaerahTextField;
    private javax.swing.JLabel dashboardSidePanel;
    private javax.swing.JPanel dataVolunteerJudulPanel;
    private javax.swing.JLabel deleteSidePanel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorNamaPencacah;
    private javax.swing.JLabel errorNamaPengawas;
    private javax.swing.JLabel errorNamaResponden;
    private javax.swing.JLabel errorTanggalPencacahan;
    private javax.swing.JLabel errorTanggalPengawasan;
    private javax.swing.JButton hapusButton;
    private javax.swing.JPanel insertSidePanel;
    private javax.swing.JLabel insertSidePanel2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JComboBox<String> jenisKelamin;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JTextField kelasTextField;
    private javax.swing.JPanel keteranganVolunteerJudulPanel;
    private javax.swing.JLabel logoutSidePanel;
    private javax.swing.JPanel logoutSidePanel2;
    private javax.swing.JLabel namaLengkapLabel;
    private javax.swing.JTextField namaLengkapTextField;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JLabel tanggalMasukLabel;
    private javax.swing.JTextField tanggalMasukTextField;
    private javax.swing.JTextField umurTextField;
    private javax.swing.JPanel viewSidePanel;
    private javax.swing.JLabel viewSidePanel3;
    // End of variables declaration//GEN-END:variables
}
