/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
//import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import database.connection;
//import database.Database;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
//import java.awt.Toolkit;
//import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
//import java.util.List;
//import javax.swing.DefaultComboBoxModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author BLESSY
 */

public class UserView extends javax.swing.JFrame {
    
    private static String username;
    private Connection conn;
    private PreparedStatement pstmt;
    private ResultSet rs;
    private String id;

    public UserView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        conn=connection.getConnection();
//        getProvinsi();
        viewTable();
    }
    
    public void close() {
//        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
//        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    this.dispose();
    }
    
    public static void openUserView(String username) {
        UserView.username = username;
        main();
  
    }
    
    public static void main(String[] args) {
        openUserView("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        dashboardSidePanel = new javax.swing.JLabel();
        bpsLogo = new javax.swing.JLabel();
        logoutSidePanel2 = new javax.swing.JPanel();
        logoutSidePanel = new javax.swing.JLabel();
        viewSidePanel1 = new javax.swing.JPanel();
        viewSidePanel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        exportCsvButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ContentTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 102, 0));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dashboardSidePanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dashboardSidePanel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardSidePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardSidePanel.setText("DASHBOARD");
        dashboardSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardSidePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 290, 40));

        bpsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pmkl_k.jpg"))); // NOI18N
        jPanel15.add(bpsLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        logoutSidePanel2.setBackground(new java.awt.Color(156, 171, 180));
        logoutSidePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutSidePanel2MouseClicked(evt);
            }
        });

        logoutSidePanel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        logoutSidePanel.setForeground(new java.awt.Color(255, 255, 255));
        logoutSidePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutSidePanel.setText("LOGOUT");
        logoutSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutSidePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logoutSidePanel2Layout = new javax.swing.GroupLayout(logoutSidePanel2);
        logoutSidePanel2.setLayout(logoutSidePanel2Layout);
        logoutSidePanel2Layout.setHorizontalGroup(
            logoutSidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutSidePanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        logoutSidePanel2Layout.setVerticalGroup(
            logoutSidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutSidePanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel15.add(logoutSidePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 290, 40));

        viewSidePanel1.setBackground(new java.awt.Color(156, 171, 180));
        viewSidePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSidePanel1MouseClicked(evt);
            }
        });

        viewSidePanel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        viewSidePanel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewSidePanel4.setText("VIEW DATA");
        viewSidePanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSidePanel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viewSidePanel1Layout = new javax.swing.GroupLayout(viewSidePanel1);
        viewSidePanel1.setLayout(viewSidePanel1Layout);
        viewSidePanel1Layout.setHorizontalGroup(
            viewSidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewSidePanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewSidePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        viewSidePanel1Layout.setVerticalGroup(
            viewSidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewSidePanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(viewSidePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel15.add(viewSidePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, 40));

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 289, 860));

        jPanel8.setBackground(new java.awt.Color(255, 102, 0));

        jLabel6.setBackground(new java.awt.Color(242, 237, 215));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VIEW [USER]");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel6)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1250, -1));

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));

        exportCsvButton1.setText("Export File (.csv)");
        exportCsvButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportCsvButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BLOK I. Data Volunteer");

        ContentTable.setBackground(new java.awt.Color(204, 255, 204));
        ContentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Lengkap", "Nim", "Kelas", "Asal Daerah", "Email", "Umur", "Jenis Kelamin", "Tanggal Masuk", "Alasan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ContentTable.getTableHeader().setReorderingAllowed(false);
        ContentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ContentTable);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BLOK II. Keterangan Volunteer");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exportCsvButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(exportCsvButton1)
                .addGap(71, 71, 71))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 1250, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardSidePanelMouseClicked
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null, "Anda sudah berada disini", "Sudah sampai", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_dashboardSidePanelMouseClicked
    
    private void viewTable() {
    DefaultTableModel tb = new DefaultTableModel();

    tb.addColumn("ID"); // Add the hidden column "ID"
    tb.addColumn("No");
    tb.addColumn("Nama Lengkap");
    tb.addColumn("NIM");
    tb.addColumn("Kelas");
    tb.addColumn("Asal Daerah");
    tb.addColumn("Email");
    tb.addColumn("Umur");
    tb.addColumn("Jenis Kelamin");
    tb.addColumn("Tanggal Masuk");
    tb.addColumn("Alasan");

    ContentTable.setModel(tb);

       try {
           // Mengambil data dari database
           Statement stat = conn.createStatement();
           ResultSet rs = stat.executeQuery("SELECT * FROM content");
           int i = 1;
           while (rs.next()) {
            tb.addRow(new Object[]{
                rs.getString("id"), // Add the ID value to the hidden column
                i, // Assuming 'i' is an incrementing integer for row number
                rs.getString("nama_lengkap"),
                rs.getString("nim"),
                rs.getString("kelas"),
                rs.getString("asal_daerah"),
                rs.getString("email"),
                rs.getString("umur"),
                rs.getString("jenis_kelamin"),
                rs.getString("tanggal_masuk"),
                rs.getString("alasan")
            });
            i++;
        }

           // Hide the "ID" column
            TableColumnModel columnModel = ContentTable.getColumnModel();
            TableColumn idColumn = columnModel.getColumn(0);
            columnModel.removeColumn(idColumn);

       } catch (Exception e) {
           System.out.println(e);
       }
   }
    
    public void openFile(String file){
            try{
                File path = new File(file);
                Desktop.getDesktop().open(path);
            }catch(IOException ioe){
                System.out.println(ioe);
            }
    }
    
    
    private void logoutSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutSidePanelMouseClicked
        // TODO add your handling code here:
        // Display a confirmation dialog
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        // Check the user's choice
        if (option == JOptionPane.YES_OPTION) {
            close();
            SignIn.openSignIn();
        }
    }//GEN-LAST:event_logoutSidePanelMouseClicked

    private void logoutSidePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutSidePanel2MouseClicked
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        // Check the user's choice
        if (option == JOptionPane.YES_OPTION) {
            close();
            SignIn.openSignIn();
        }
    }//GEN-LAST:event_logoutSidePanel2MouseClicked

    private void viewSidePanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSidePanel4MouseClicked
        // TODO add your handling code here:
        close();
        UserView.openUserView(username);
    }//GEN-LAST:event_viewSidePanel4MouseClicked

    private void viewSidePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSidePanel1MouseClicked
        // TODO add your handling code here:
        close();
        UserView.openUserView(username);
    }//GEN-LAST:event_viewSidePanel1MouseClicked

    private void exportCsvButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportCsvButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file save");
        fileChooser.setFileFilter(new FileNameExtensionFilter("CSV Files", "csv")); // Menambahkan filter file CSV
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Menambahkan ekstensi .csv jika belum ada
            if (!filePath.toLowerCase().endsWith(".csv")) {
                fileToSave = new File(filePath + ".csv");
            }

            try {
                FileWriter fw = new FileWriter(fileToSave);
                BufferedWriter bw = new BufferedWriter(fw);

                // Menulis judul kolom
                for (int i = 0; i < ContentTable.getColumnCount(); i++) {
                    bw.write(ContentTable.getColumnName(i) + ",");
                }
                bw.newLine();

                // Menulis data ke file
                for (int i = 0; i < ContentTable.getRowCount(); i++) {
                    for (int j = 0; j < ContentTable.getColumnCount(); j++) {
                        Object value = ContentTable.getValueAt(i, j);
                        if (value != null) {
                            bw.write(value.toString() + ",");
                        } else {
                            bw.write("NULL,");
                        }
                    }
                    bw.newLine();
                }

                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(this, "SUCCESSFULLY SAVED", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

                // Membuka file setelah penulisan selesai
                openFile(fileToSave.getAbsolutePath());
            } catch (IOException ex) {
                //                JOptionPane.showMessageDialog(this, "ERROR", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_exportCsvButton1ActionPerformed

    private void ContentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContentTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ContentTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ContentTable;
    private javax.swing.JLabel bpsLogo;
    private javax.swing.JLabel dashboardSidePanel;
    private javax.swing.JButton exportCsvButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoutSidePanel;
    private javax.swing.JPanel logoutSidePanel2;
    private javax.swing.JPanel viewSidePanel1;
    private javax.swing.JLabel viewSidePanel4;
    // End of variables declaration//GEN-END:variables

    
}
